import '../src/style/globals.css' //load global style on storybook
import { withThemeByClassName } from '@storybook/addon-themes';
import type { Preview } from '@storybook/react'

const preview: Preview = {
  tags: ['autodocs'], // set autogenerated doc for all stories
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i
      }
    }
  },
  decorators: [
    withThemeByClassName({
      themes: {
        light: 'light',
        dark: 'dark',
      },
      defaultTheme: 'light',
    }),
  ],
}

export default preview
