import type { Preview } from '@storybook/react'

const preview: Preview = {
  tags: ['autodocs'], // set autogenerated doc for all stories
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i
      }
    }
  }
}

export default preview
