name: 'Setup Node.js and pnpm'
description: 'Configure Node.js et pnpm avec installation des dépendances'
inputs:
  node-version:
    description: 'Version de Node.js'
    required: false
    default: '20'
  pnpm-version:
    description: 'Version de pnpm'
    required: false
    default: '10'

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
