name: Lint and Prettier
on: [push]

jobs:
  lint_and_prettier:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [lint, prettier:check]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js et pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: '20'
          pnpm-version: '10'

      - name: Run ${{matrix.task}}
        run: pnpm ${{matrix.task}}
